WITH MAX_SIZE_OF_COLONY AS (
    SELECT MAX(SIZE_OF_COLONY) MAX_SIZE, YEAR(DIFFERENTIATION_DATE) YEAR
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)
SELECT 
    MS.YEAR, 
    (MS.MAX_SIZE - ED.SIZE_OF_COLONY) YEAR_DEV, 
    ED.ID
FROM ECOLI_DATA ED
JOIN MAX_SIZE_OF_COLONY MS ON YEAR(ED.DIFFERENTIATION_DATE) = MS.YEAR
ORDER BY MS.YEAR, YEAR_DEV;